# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_subject',
        ),
    ]
