# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170925_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar_id',
            field=models.IntegerField(default=1),
        ),
    ]
