# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170925_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
