# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170926_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_question',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
