# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170926_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ManyToManyField(default=0, related_name='_post_parent_id_+', to='forum.Post'),
        ),
    ]
