# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20170926_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
