# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20170926_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parentID', to='forum.Post'),
        ),
    ]
