# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20170926_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(default=models.AutoField(primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, related_name='parentID', to='forum.Post'),
        ),
    ]
