# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20170926_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
