# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_post_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentID', to='forum.Post'),
        ),
    ]
