# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20170926_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='level',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentID', to='forum.Post'),
        ),
    ]
