# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20170927_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
