# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_post_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageNumberOfCharactersPerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thoughtfulness_Score',
            fields=[
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forum.Post')),
                ('post_content', models.TextField()),
                ('thoughtfulness_score', models.FloatField()),
            ],
        ),
    ]
